### ISSUE TITLE
Request: Unread Lines in World Tabs 

### ISSUE THREAD

**Issue by nimriye** [BeipDev/BeipMU#59]
I mentioned this a bit in the Discord but should really log a ticket!

MUSHclient and Atlantis have a feature where a counter of 'unread lines in this window' will appear on each inactive world tab, as new lines arrive in those worlds.

So for example, if you are coding in one window, you can glance at the tabs for the other windows and see if the activity there is a pose (suddenly 15 new lines arrive) or just a random message that probably doesn't need attention (1 new line), or if someone is spamming really hard (300 new lines).

A screenshot from MUSHclient displaying the feature looks like this https://www.gammon.com.au/images/gs6/gs61.gif

The first tab is active, and the other two show (24) to indicate 24 new lines have arrived in those windows since you last checked them.

Thanks for considering!

**Comment by nimriye** [comment]
Thanks! Yeah, it does reset/mark all as read once you go to the window, at least the way it works in Atlantis/MUSHclient.

**Comment by nimriye** [comment]
Two thoughts on the unread lines/new activity marker:

1) For the Unread Lines counter in the window tabs: in Atlantis, the 'mark on read' effect happens as soon as you click on the tab itself. So the (+20) disappears when you click on the tab, rather than the current behavior where you need to click back out to clear the (+20).

The New Activity bar would of course stay until you click back out of the tab, so you can see where the activity begins, but the (+20) on the tab clears once you click on the tab.

2) Some customization options for the 'new activity' bar would be great. A lot of clients even just make it a line of text, from what I see, usually to the tune of `---------- New Activity ----------`

Failing that, maybe an option to change the bar color for now.

**Comment by BeipDev** [comment]
1. This should be fixed to vanish when you click on the window
2. I'm not sure about this one, since if we add ways to customize it then we can't easily change the appearance later without breaking the customizations. I can try and get the horizontal rule version working, would that be nicer visually?

**Comment by nimriye** [comment]
It would be nicer visually for me personally! I know I do like the way Discord does the separator:

![image](https://user-images.githubusercontent.com/40511921/52612795-45d40280-2e59-11e9-902b-d0e5a9e2d119.png)

Something like that. I think it would be less obtrusive visually than a solid bar, while still showing a clear delineation. Thanks for considering either way!
